### ISSUE TITLE
php artisan migrate が失敗します

### ISSUE THREAD

**Issue by mikami-satoshi** [MurahashiKatsuya/chouseikun#4]
PDOException  : SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

  at /var/www/chouseikun/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
    66|         if (class_exists(PDOConnection::class) && ! $this->isPersistentConnection($options)) {
    67|             return new PDOConnection($dsn, $username, $password, $options);
    68|         }
    69| 
  > 70|         return new PDO($dsn, $username, $password, $options);
    71|     }
    72| 
    73|     /**
    74|      * Determine if the connection is persistent.

  Exception trace:

  1   PDO::__construct("mysql:host=mysql;port=3306;dbname=chouseikun", "develop", "secret", [])
      /var/www/chouseikun/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  2   Illuminate\Database\Connectors\Connector::createPdoConnection("mysql:host=mysql;port=3306;dbname=chouseikun", "develop", "secret", [])
      /var/www/chouseikun/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:100

  Please use the argument -v to see more details.

**Comment by MurahashiKatsuya** [comment]
@mikami-satoshi 
すみません。
確認します。

**Comment by mikami-satoshi** [comment]
@MurahashiKatsuya 
申し訳ありません！再度git cloneし、実行したところ起動出来ました。
クローズさせていただきます。
